name: denizsalman
description: "Deniz Salman"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  cupertino_icons: ^1.0.6
  mouse_parallax: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg.json
